### ISSUE TITLE
Package v0.8.6 rejected by Chocolatey

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/chocolatey-latexml#14] opened 2021-11-15 04:29 UTC
'latexml' is Rejected.
chocolatey-ops left the following comment(s):

Unfortunately there has not been progress to move latexml v0.8.6 towards an approved status within 15 days after the last review message, so we need to close (reject) the package version at this time. If you want to pick this version up and move it towards approval in the future, use the contact site admins link on the package page and we can move it back into a submitted status so you can submit updates.

Status Change - Changed status of package from 'submitted' to 'rejected'.

The package was rejected by chocolatey-ops on 14 Nov 2021.

**Comment by CAMOBAP** [comment] 2021-11-15 06:09
Both times tests failed on 

Failures
2021-10-11 07:11:58,988 2400 [ERROR] -  - imagemagick.tool (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\imagemagick.tool\tools\chocolateyInstall.ps1'.
 See log for details.

Initially I thought that it some network issue, we faced with it from time to time, but looks like the issue is permanent. And start appears recently

There are also ` imagemagick` and `imagemagick.app` dependencies, but `imagemagick.tool` looks like exactly right one, I

Next steps:
 - [x] research for known `imagemagick.tool` issues
 - [x] rerun our workflow to reproduce it on our CI
 - [x] fill a but or use some workaround

**Comment by CAMOBAP** [comment] 2021-11-15 08:13
Oh... issue on our end I hardcoded dependencies version which doesn't exists anymore, I will change it to less strict

**Comment by CAMOBAP** [comment] 2021-11-15 09:55
Waiting for 0.8.6 version remove from chocolatey by admins, till this I have pushed 0.8.5 to verify the fix

**Comment by CAMOBAP** [comment] 2021-11-15 11:13
https://github.com/bdukes/Chocolatey-Packages/issues/35 - waiting for reply

**Comment by CAMOBAP** [comment] 2021-11-20 08:34
0.8.5 was approved, looks like 0.8.6 lost ( because no one is respond, closing this ticket

**Closed as completed by CAMOBAP** 2021-11-20 08:34 UTC
Labels: bug
